language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
before_script: 
  - dotnet restore
script:
  - dotnet build StoredProcedureEFCore -c Release
  - dotnet test StoredProcedureEFCore.Tests