language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.300
before_script: 
  - dotnet restore
script:
  - dotnet build StoredProcedureEFCore -c Release
  - dotnet test StoredProcedureEFCore.Tests